context:
  name: py-retrieve
  version: 20251206

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: git@github.jpl.nasa.gov:MUSES-Processing/py-retrieve.git
    rev: 9f80babfd740bf642aee947c4ee0776d064c1207
    
build:
  number: 0
  script:
    - python -m pip install . --no-deps --ignore-installed --no-cache-dir --no-index -vvv

requirements:
  build:
    - git
  host:
    - pip
    - numpy ${{ numpy }}
    - python ${{ python }}
    - setuptools
    - click
    - numpy
    - scipy
    - mpi4py
    - netCDF4
    - h5py
    - pyhdf
    - muses-oss
    - muses-vlidort
    - muses-rrs
  run:
    - pip
    - numpy ${{ numpy }}
    - python ${{ python }}
    - setuptools
    - click
    - numpy
    - scipy
    - mpi4py
    - netCDF4
    - h5py
    - pyhdf
    - muses-oss
    - muses-vlidort
    - muses-rrs
    
    
about:
  summary: A number of the muses python libraries
  license: LicenseRef-UNLICENSED
  description: |
    Py-retrieve code

    Currently:
    Copyright (c) 2025, California Institute of Technology ("Caltech"). U.S.
    Government sponsorship acknowledged. All rights reserved.      
    
