context:
  name: py-retrieve
  version: 20251011

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: git@github.jpl.nasa.gov:MUSES-Processing/py-retrieve.git
    rev: d75e4c888fb1a6d67c5b53ef480a8e393666dd65
    
build:
  number: 0
  script:
    - python -m pip install . --no-deps --ignore-installed --no-cache-dir --no-index -vvv

requirements:
  build:
    - git
  host:
    - pip
    - numpy ${{ numpy }}
    - python ${{ python }}
    - setuptools
    - click
    - numpy
    - scipy
    - mpi4py
    - netCDF4
    - h5py
    - pyhdf
    - libgfortran4-compatiblity
    - muses-oss
    - muses-vlidort
  run:
    - pip
    - numpy ${{ numpy }}
    - python ${{ python }}
    - setuptools
    - click
    - numpy
    - scipy
    - mpi4py
    - netCDF4
    - h5py
    - pyhdf
    - libgfortran4-compatiblity
    - muses-oss
    - muses-vlidort
    
    
about:
  summary: A number of the muses python libraries
  license: LicenseRef-UNLICENSED
  description: |
    Most of the amuse-me pipeline is code that doesn't change much.
    We have one package just to install this easily. This is everything
    *except* refractor-framework, refractor-muses, and py-retrieve. This
    other packages get updated at a different cadence, so we treat those
    as separate.

    Currently:
    Copyright (c) 2025, California Institute of Technology ("Caltech"). U.S.
    Government sponsorship acknowledged. All rights reserved.      
    
