context:
  name: muses-rrs
  version: 1.01

package:
  name: ${{ name }}
  version: ${{ version }}

# Note for this checkout to work here you need to have a public key that
# matches between jpl github and the JPL cae-artifactory.jpl.nasa.gov.
# See https://github.jpl.nasa.gov/MUSES-Processing/muses-quick-docs/blob/master/git-lfs.md
# We have a setup on pistol and rifle as ~/.ssh/config
source:
  - git: ssh://git@github.jpl.nasa.gov/MUSES-Processing/muses-rrs.git
    rev: 80769e91ab13dfce56b51b90203a3074359e325f
    
build:
  number: 0
  script:
    - bash configure.sh
    # CMake looking for .f90, not .F90
    - mv lib/M_CLI2/src/M_CLI2.F90 lib/M_CLI2/src/M_CLI2.f90
    - cd build/release
    - cmake -DCMAKE_BUILD_TYPE=Release ../..
    - make
    - mkdir -p $PREFIX/bin
    - cp ring/ring_cli $PREFIX/bin

requirements:
  build:
    - ${{ compiler('fortran') }}
    - cmake ${{ cmake }}
  host:
  run:

about:
  homepage: https://github.jpl.nasa.gov/MUSES-Processing/muses-rrs
  summary: MUSES Ring cli
  license: LicenseRef-UNLICENSED
  description: |
    https://github.jpl.nasa.gov/MUSES-Processing/muses-quick-docs
    Currently:
    Copyright (c) 2025, California Institute of Technology ("Caltech"). U.S.
    Government sponsorship acknowledged. All rights reserved.
    
